name = "covenMerge"
defaultTargets = ["CovenMerge", "mergeRunner"]

[leanOptions]
linter.unusedSectionVars = false

[[lean_lib]]
name = "CovenMerge"

[[lean_exe]]
name = "mergeRunner"
root = "MergeRunner"
