import CovenStorelog

#print axioms CovenStorelog.Examples.CircleDeletion.valid_history
#print axioms CovenStorelog.Examples.CircleDeletion.causal_arrivals
#print axioms CovenStorelog.Examples.CircleDeletion.shared_key_conflict
#print axioms CovenStorelog.Examples.CircleDeletion.earlier_rotation_applies
#print axioms CovenStorelog.Examples.CircleDeletion.alone_valid
#print axioms CovenStorelog.Examples.CircleDeletion.alone_conflict
#print axioms CovenStorelog.Examples.CircleDeletion.removal_beats_rename

#print axioms CovenStorelog.publication_requires_seal
#print axioms CovenStorelog.sealing_requires_approval
#print axioms CovenStorelog.dropped_join_declined
#print axioms CovenStorelog.Examples.seal_then_entry
#print axioms CovenStorelog.Examples.carol_join_declined

#print axioms CovenStorelog.effect_created
#print axioms CovenStorelog.scan_root_suffix
#print axioms CovenStorelog.scan_root
#print axioms CovenStorelog.settleN_created
#print axioms CovenStorelog.resolve_created
#print axioms CovenStorelog.admin_invariant
#print axioms CovenStorelog.closed_has_admin

#print axioms CovenStorelog.scan_views_congr
#print axioms CovenStorelog.settleN_views_congr
#print axioms CovenStorelog.settle_views_congr
#print axioms CovenStorelog.resolve_eq
#print axioms CovenStorelog.range_filter_bound
#print axioms CovenStorelog.resolve_bound_independent

#print axioms CovenStorelog.Examples.Gifts.valid_history
#print axioms CovenStorelog.Examples.Gifts.causal_arrivals
#print axioms CovenStorelog.Examples.Gifts.removal_names_no_circle
#print axioms CovenStorelog.Examples.Gifts.conflicts
#print axioms CovenStorelog.Examples.Gifts.first_pass
#print axioms CovenStorelog.Examples.Gifts.carol_stays

#print axioms CovenStorelog.before_irrefl
#print axioms CovenStorelog.before_trans
#print axioms CovenStorelog.before_total
#print axioms CovenStorelog.before_asymm
#print axioms CovenStorelog.store_removal_circle_add

#print axioms CovenStorelog.Accounting.skip
#print axioms CovenStorelog.Accounting.keep
#print axioms CovenStorelog.Accounting.drop
#print axioms CovenStorelog.scan_accounting
#print axioms CovenStorelog.settleN_accounting
#print axioms CovenStorelog.resolve_partition

#print axioms CovenStorelog.step_spec
#print axioms CovenStorelog.closed_insert
#print axioms CovenStorelog.insert_entrySet
#print axioms CovenStorelog.run_isSpec
#print axioms CovenStorelog.causal_ready
#print axioms CovenStorelog.timestampOrder_causal
#print axioms CovenStorelog.full_history_causal
#print axioms CovenStorelog.author_view_reached
#print axioms CovenStorelog.author_past_causal
#print axioms CovenStorelog.isSpec_unique
#print axioms CovenStorelog.storelog_converges

#print axioms CovenStorelog.Examples.circle_examples_valid
#print axioms CovenStorelog.Examples.circle_created_by_member
#print axioms CovenStorelog.Examples.circle_renamed
#print axioms CovenStorelog.Examples.circle_deleted
#print axioms CovenStorelog.Examples.circle_delete_beats_reset
#print axioms CovenStorelog.Examples.circle_key_rotation
#print axioms CovenStorelog.Examples.circle_leaving
#print axioms CovenStorelog.Examples.outsider_cannot_manage
#print axioms CovenStorelog.Examples.empty_circle_deleted
#print axioms CovenStorelog.Examples.member_removal_updates_circles
#print axioms CovenStorelog.Examples.store_removal_beats_circle_add

#print axioms CovenStorelog.Examples.rotation_examples_valid
#print axioms CovenStorelog.Examples.same_circle_rotations_conflict
#print axioms CovenStorelog.Examples.different_circle_rotations_both_apply
#print axioms CovenStorelog.Examples.store_rotation_beats_later_circle_rotation
#print axioms CovenStorelog.Examples.repeated_store_removals_keep_both
#print axioms CovenStorelog.Examples.repeated_circle_removals_keep_both

#print axioms CovenStorelog.Examples.member_examples_valid
#print axioms CovenStorelog.Examples.opening_log
#print axioms CovenStorelog.Examples.example_add_and_promote
#print axioms CovenStorelog.Examples.example_member_removal_beats_phone
#print axioms CovenStorelog.Examples.new_device_registers_itself
#print axioms CovenStorelog.Examples.device_removal_checks_owner
#print axioms CovenStorelog.Examples.example_lower_role
#print axioms CovenStorelog.Examples.example_mutual_removal
#print axioms CovenStorelog.Examples.example_carol
#print axioms CovenStorelog.Examples.carol_device
#print axioms CovenStorelog.Examples.equal_adds_combine
#print axioms CovenStorelog.Examples.three_admins
#print axioms CovenStorelog.Examples.removed_author_view
#print axioms CovenStorelog.Examples.dropped_removal_allows_phone

#print axioms CovenStorelog.Examples.history_valid
#print axioms CovenStorelog.Examples.valid_history
#print axioms CovenStorelog.Examples.causal_arrivals
#print axioms CovenStorelog.Examples.entries_concurrent
#print axioms CovenStorelog.Examples.each_entry_allowed_in_its_view
#print axioms CovenStorelog.Examples.first_pass_drops_add
#print axioms CovenStorelog.Examples.second_pass_drops_removal
#print axioms CovenStorelog.Examples.losing_removal_discards_add
#print axioms CovenStorelog.Examples.add_has_no_surviving_opponent
#print axioms CovenStorelog.Examples.dropped_add_meets_conditions

#print axioms CovenStorelog.causalCheck_sound
#print axioms CovenStorelog.validCheck_sound
#print axioms CovenStorelog.every_order

#print axioms CovenStorelog.Examples.version_examples_valid
#print axioms CovenStorelog.Examples.same_version_snapshot
#print axioms CovenStorelog.Examples.identical_version_raises
#print axioms CovenStorelog.Examples.version_raised
#print axioms CovenStorelog.Examples.store_reset_tie
#print axioms CovenStorelog.Examples.circle_reset_tie
#print axioms CovenStorelog.Examples.equal_resets_combine
#print axioms CovenStorelog.Examples.later_reset
#print axioms CovenStorelog.Examples.reset_raise_examples_valid
#print axioms CovenStorelog.Examples.concurrent_reset_and_raise
#print axioms CovenStorelog.Examples.causal_reset_and_raise
#print axioms CovenStorelog.Examples.circle_reset_and_store_raise

#print axioms CovenStorelog.checkedEffect_sound
#print axioms CovenStorelog.scan_state
#print axioms CovenStorelog.settleN_state
#print axioms CovenStorelog.resolve_safe
#print axioms CovenStorelog.resolve_references
#print axioms CovenStorelog.scan_kept
#print axioms CovenStorelog.settleN_kept
#print axioms CovenStorelog.kept_received
#print axioms CovenStorelog.authority_uses_author_view
#print axioms CovenStorelog.devices_have_members
#print axioms CovenStorelog.circles_have_members
#print axioms CovenStorelog.circles_nonempty
#print axioms CovenStorelog.device_add_authority
#print axioms CovenStorelog.device_removal_authority
#print axioms CovenStorelog.circle_delete_authority

#print axioms CovenStorelog.lookup_some_mem
#print axioms CovenStorelog.lookup_erase_same
#print axioms CovenStorelog.lookup_erase_other
#print axioms CovenStorelog.lookup_put
#print axioms CovenStorelog.member_put
#print axioms CovenStorelog.member_erase
#print axioms CovenStorelog.references_empty
#print axioms CovenStorelog.References.putMembers
#print axioms CovenStorelog.References.withDevices
#print axioms CovenStorelog.References.withCircles
#print axioms CovenStorelog.References.putCircle
#print axioms CovenStorelog.References.eraseCircle
#print axioms CovenStorelog.withoutMember_members
#print axioms CovenStorelog.References.removeMember
#print axioms CovenStorelog.effect_references

#print axioms CovenStorelog.scan_progress
#print axioms CovenStorelog.countP_lt_of
#print axioms CovenStorelog.restart_decreases
#print axioms CovenStorelog.settleN_total

#print axioms CovenStorelog.settle_eq_some
#print axioms CovenStorelog.authorViews_at

#print axioms CovenStorelog.Examples.audience_updates_valid
#print axioms CovenStorelog.Examples.each_audience_has_its_version
#print axioms CovenStorelog.Examples.circle_updates_valid
#print axioms CovenStorelog.Examples.circle_higher_version_wins
#print axioms CovenStorelog.Examples.circle_equal_version_snapshots
#print axioms CovenStorelog.Examples.circle_reset_raise_valid
#print axioms CovenStorelog.Examples.circle_concurrent_reset_and_raise
#print axioms CovenStorelog.Examples.circle_causal_reset_and_raise
#print axioms CovenStorelog.Examples.circle_raise_and_other_reset
#print axioms CovenStorelog.Examples.circle_raise_authority_examples_valid
#print axioms CovenStorelog.Examples.outside_admin_cannot_repeat_raise
#print axioms CovenStorelog.Examples.removed_circle_member_can_raise_concurrently
#print axioms CovenStorelog.Examples.derived_circle_deletion_beats_raise
#print axioms CovenStorelog.Examples.explicit_circle_deletion_beats_raise
#print axioms CovenStorelog.circle_raise_authority

#print axioms CovenStorelog.Action.isCreation_true
#print axioms CovenStorelog.Examples.access_examples_valid
#print axioms CovenStorelog.Examples.replacement_then_removal
#print axioms CovenStorelog.Examples.removal_defeats_access

#print axioms CovenStorelog.ReplayPrefix.scan_append
#print axioms CovenStorelog.ReplayPrefix.complete_frame
#print axioms CovenStorelog.ReplayPrefix.reseed
#print axioms CovenStorelog.ReplayPrefix.transport
#print axioms CovenStorelog.ReplayPrefix.suffix_frame
#print axioms CovenStorelog.ReplayPrefix.after_complete
#print axioms CovenStorelog.ReplayPrefix.settleN_prefix
#print axioms CovenStorelog.ReplayPrefix.settle_prefix
#print axioms CovenStorelog.Finality.read_no_conflict
#print axioms CovenStorelog.Finality.preference_strict
#print axioms CovenStorelog.Finality.tooLate_iff
#print axioms CovenStorelog.Finality.authorViews_at
#print axioms CovenStorelog.Finality.partition
#print axioms CovenStorelog.Finality.read_landed_before
#print axioms CovenStorelog.Finality.old_closed
#print axioms CovenStorelog.Finality.quiet_reads
#print axioms CovenStorelog.Finality.survivor_reads_old
#print axioms CovenStorelog.Finality.old_drop_fixed
#print axioms CovenStorelog.Finality.range_split
#print axioms CovenStorelog.Finality.resolve_old_prefix
#print axioms CovenStorelog.Finality.stability
#print axioms CovenStorelog.Finality.time_complete
#print axioms CovenStorelog.Finality.late_atTime
#print axioms CovenStorelog.Finality.quiet_atTime
#print axioms CovenStorelog.Finality.storage_stability
#print axioms CovenStorelog.Finality.progress
#print axioms CovenStorelog.Finality.received_spec
#print axioms CovenStorelog.Finality.agreement
#print axioms CovenStorelog.Finality.drop_agreement
#print axioms CovenStorelog.Finality.drop_decided
#print axioms CovenStorelog.Finality.device_stability
#print axioms CovenStorelog.Finality.normal_not_dropped
#print axioms CovenStorelog.Finality.Examples.resets_valid
#print axioms CovenStorelog.Finality.Examples.history_valid
#print axioms CovenStorelog.Finality.Examples.causal_deliveries
#print axioms CovenStorelog.Finality.Examples.delayed_delivery_counterexample
#print axioms CovenStorelog.Finality.Examples.missing_drop_witness
#print axioms CovenStorelog.Finality.Examples.exact_boundaries
#print axioms CovenStorelog.Finality.Examples.arrived_orders_agree
#print axioms CovenStorelog.Finality.Examples.chain_valid
#print axioms CovenStorelog.Finality.Examples.quiet_window_needed
#print axioms CovenStorelog.Finality.Examples.backdated_valid
#print axioms CovenStorelog.Finality.Examples.drop_rule_needed
#print axioms CovenStorelog.Finality.Examples.one_change_no_delayed_flip
#print axioms CovenStorelog.Finality.Examples.decided_conflicts
#print axioms CovenStorelog.Finality.Examples.finite_valid
#print axioms CovenStorelog.Finality.Examples.cutoff_receipt_needed

#print axioms CovenStorelog.CurrentReplay.empty_cause_latest
#print axioms CovenStorelog.CurrentReplay.finished_circles_nonempty
#print axioms CovenStorelog.CurrentReplay.kept_authorized
#print axioms CovenStorelog.CurrentReplay.rotation_authority
#print axioms CovenStorelog.CurrentReplay.rotations_conflict_with_nothing
#print axioms CovenStorelog.CurrentReplay.equal_received
#print axioms CovenStorelog.CurrentExamples.concurrent_addition_populates_empty_circle
#print axioms CovenStorelog.CurrentExamples.empty_circle_cause
#print axioms CovenStorelog.CurrentExamples.rotation_entries
#print axioms CovenStorelog.CurrentExamples.removed_rotator_keeps_recorded_authority
#print axioms CovenStorelog.CurrentExamples.explicit_deletion_still_wins

#print axioms CovenStorelog.CurrentExamples.deleted_circle_keeps_rotation

#print axioms CovenStorelog.Horizon.advance_iff
#print axioms CovenStorelog.Horizon.accumulated_iff
#print axioms CovenStorelog.Horizon.final_iff_before_horizon
#print axioms CovenStorelog.Horizon.advance_never_back
#print axioms CovenStorelog.Horizon.horizon_never_back
#print axioms CovenStorelog.Horizon.horizon_mono_checks
#print axioms CovenStorelog.Horizon.recovered_iff
#print axioms CovenStorelog.Horizon.recovered_never_back
#print axioms CovenStorelog.Horizon.final_stays_final
#print axioms CovenStorelog.Horizon.ties_together
#print axioms CovenStorelog.Horizon.boundary_not_final
#print axioms CovenStorelog.Horizon.failed_check_preserves
#print axioms CovenStorelog.Horizon.quiet_reads
#print axioms CovenStorelog.Horizon.survivor_reads_old
#print axioms CovenStorelog.Horizon.current_prefix
#print axioms CovenStorelog.Horizon.excluded_disposition
#print axioms CovenStorelog.Horizon.old_closed
#print axioms CovenStorelog.Horizon.current_stability
#print axioms CovenStorelog.Horizon.horizon_stability

#print axioms CovenStorelog.Horizon.Examples.tied_causal
#print axioms CovenStorelog.Horizon.Examples.tied_online
#print axioms CovenStorelog.Horizon.Examples.tied_boundaries
#print axioms CovenStorelog.Horizon.Examples.late_drop_does_not_reopen
#print axioms CovenStorelog.Horizon.Examples.inclusive_recent_window
#print axioms CovenStorelog.Horizon.Examples.earlier_window_recovered
#print axioms CovenStorelog.Horizon.Examples.latest_check_forgets_finality
#print axioms CovenStorelog.Horizon.Examples.current_replay_stays_fixed

#print axioms CovenStorelog.CurrentReplay.introduction_cases
#print axioms CovenStorelog.CurrentReplay.removals_introduce_nothing
#print axioms CovenStorelog.ReplayPolicy.read_no_conflict
#print axioms CovenStorelog.ReplayPolicy.empty_cause_latest
#print axioms CovenStorelog.ReplayPolicy.finished_circles_nonempty
#print axioms CovenStorelog.ReplayPolicy.equal_received
#print axioms CovenStorelog.ReplayPolicy.kept_authorized
#print axioms CovenStorelog.ReplayPolicy.rotation_authority
#print axioms CovenStorelog.ReplayPolicy.rotations_conflict_with_nothing
#print axioms CovenStorelog.CurrentReplay.kept_received
#print axioms CovenStorelog.CurrentReplay.tier_results
#print axioms CovenStorelog.CurrentReplay.store_removals_compatible
#print axioms CovenStorelog.CurrentReplay.resolve_safe
#print axioms CovenStorelog.CurrentReplay.admin_remains
#print axioms CovenStorelog.CurrentKeys.introduction_source
#print axioms CovenStorelog.CurrentKeys.kept_introduction_received
#print axioms CovenStorelog.CurrentKeys.kept_key_origin
#print axioms CovenStorelog.CurrentKeys.circle_key_authority
#print axioms CovenStorelog.CurrentKeys.hashFor_source
#print axioms CovenStorelog.CurrentKeys.hashFor_agrees
#print axioms CovenStorelog.CurrentKeys.accepted_bytes_unique
#print axioms CovenStorelog.CurrentKeys.other_bytes_rejected
#print axioms CovenStorelog.CurrentKeys.mismatching_copy_no_key_or_exposure
#print axioms CovenStorelog.CurrentKeys.foreign_copy_counts
#print axioms CovenStorelog.CurrentKeys.excluded_copy_unusable
#print axioms CovenStorelog.CurrentKeys.newest_mem
#print axioms CovenStorelog.CurrentKeys.selected_usable
#print axioms CovenStorelog.CurrentKeys.usable_or_pending
#print axioms CovenStorelog.CurrentKeys.selected_no_excluded_holder
#print axioms CovenStorelog.CurrentKeys.selected_no_excluded_foreign_copy
#print axioms CovenStorelog.CurrentKeys.accepted_copy_checked
#print axioms CovenStorelog.CurrentKeys.accepted_copy_authorized
#print axioms CovenStorelog.CurrentKeys.accepted_copies_unique
#print axioms CovenStorelog.CurrentKeys.accepted_bytes_stable
#print axioms CovenStorelog.CurrentKeys.conflicting_hashes_rejected
#print axioms CovenStorelog.CurrentKeys.selected_no_excluded_copy
#print axioms CovenStorelog.CurrentKeys.newest_none
#print axioms CovenStorelog.CurrentKeys.replacement_avoids_key_wait
#print axioms CovenStorelog.CurrentKeys.newest_maximal
#print axioms CovenStorelog.CurrentKeys.first_attempt_safe
#print axioms CovenStorelog.CurrentKeys.first_attempt_authorized
#print axioms CovenStorelog.CurrentKeys.selected_newest_usable
#print axioms CovenStorelog.CurrentKeyExamples.concurrent_removals_apply
#print axioms CovenStorelog.CurrentKeyExamples.both_removals_mint_nothing
#print axioms CovenStorelog.CurrentKeyExamples.excluded_dan_or_erin_retires_each_audience
#print axioms CovenStorelog.CurrentKeyExamples.removals_wait_without_fallback
#print axioms CovenStorelog.CurrentKeyExamples.remaining_members_rotate
#print axioms CovenStorelog.CurrentKeyExamples.creation_has_no_prior_circle_membership
#print axioms CovenStorelog.CurrentKeyExamples.last_admin_removal_drops
#print axioms CovenStorelog.CurrentKeyExamples.recipient_rejects_forgery
#print axioms CovenStorelog.CurrentKeyExamples.forged_foreign_box_costs_a_rotation
#print axioms CovenStorelog.CurrentKeyExamples.forged_custody_never_selected
#print axioms CovenStorelog.Horizon.key_free_horizon_stability
