pub(super) const CAPABILITY_TYPES: &[&str] = &[
    "CircleEpochAccess",
    "ClockRef",
    "CloudHome",
    "CloudSyncConnection",
    "CloudSyncCipherStateAccess",
    "Database",
    "DeviceIdentityCustody",
    "EncryptionService",
    "Hlc",
    "MasterKeyCustody",
    "OAuthClients",
    "OwnStreamAuthorship",
    "Runtime",
    "SnapshotDatabaseImage",
    "StoreDatabase",
    "StoreDir",
    "StoreKeys",
    "UserKeypair",
    "CloudSyncObjectStorage",
];

// Directory identity is fixed when an owner graph is composed. Runtime owners
// use the filesystem capability they retain; accepting another directory would
// let callers combine state from different stores.
pub(super) const CONSTRUCTION_ONLY_CAPABILITY_TYPES: &[&str] = &["StoreDir"];

// These are configuration, value, transfer, and proof objects which happen to
// name a retained capability in their fields. They carry state between
// operations; they do not own the capability's lifetime.
pub(super) const NON_OWNER_TYPES: &[&str] = &[
    "AdmittedStoreCloudConfig",
    "AdmittedStoreCloudHome",
    "AuthorizedMembershipRevocation",
    "BlobSpoolProtection",
    "CircleAckPublicationInput",
    "CloudCipher",
    "ConnectionThread",
    "CreatedPayloadFiles",
    "CreatedSnapshot",
    "InitializedStore",
    "IdentityCustody",
    "KeyCustody",
    "LocalCommitBase",
    "ProtocolObjectContext",
    "RemoteBlobSourceInner",
    "ResolvedBlobAccess",
    "ResolvedBlobConnection",
    "SnapshotCut",
    "StoreRecords",
];

// Public API namespaces borrow a retained owner without becoming a separately
// retained service. They expose the root's intended host-facing capability.
pub(super) const BORROWED_FACADE_TYPES: &[&str] =
    &["Circles", "StoreCircleCommands", "StoreDeviceJoinTransport"];

pub(super) const RETAINED_SERVICE_ROOT_TYPES: &[&str] =
    &["CovenHandle", "CovenReadHandle", "Database", "DatabaseCore"];

// These owners are deliberately created for one operation. They may be fields
// of a retained service, but the type itself does not name that retained role.
pub(super) const OPERATION_SCOPED_OWNER_TYPES: &[&str] = &[
    "AuthorizedStore",
    "AuthorizedWriterOperation",
    "CircleEpochAccess",
    "CirclePackageAccess",
    "CloudOutboxLiveQuery",
    "ColdSnapshotDestination",
    "ColdSnapshotPreparation",
    "DestinationPayloadFiles",
    "DevicePairingHost",
    "HlcTransaction",
    "HostWriteBlobStaging",
    "LiveQuery",
    "OwnStreamAuthorship",
    "PreparedCloudHomeCredentials",
    "PreparedCloudHomeKey",
    "PreparedStoreSnapshot",
    "PreparedSyncLoopRuntime",
    "ReconfigurableLiveQuery",
    "RuntimeSlot",
    "RuntimeSlotState",
    "SnapshotPreparation",
    "StagedCloudHomeCredentials",
    "StagedMasterKeyCustody",
    "StoreOperationCommitPlan",
];

pub(super) const LIFETIME_CONSTRUCTION_AUTHORITIES: &[(&str, &str)] = &[
    ("CloudRuntime", "CloudHomeFactory"),
    ("ConnectedBlobTransitions", "SyncComponents"),
    ("CurrentRemoteBlobSource", "StoreBlobAccess"),
    ("LocalBlobTransitions", "SyncComponents"),
    ("RemoteStoreBlobAccess", "StoreBlobAccess"),
    ("Store", "StoreSync"),
    ("SyncComponents", "StoreSync"),
    ("SyncLoopHandle", "StoreSync"),
];

pub(super) const COMPOSITION_ROOTS: &[(&str, &str, &str)] = &[
    (
        "crates/coven-domain/src/joining/client.rs",
        "DeviceJoinClient",
        "new",
    ),
    (
        "crates/coven-domain/src/restoration/restore.rs",
        "RestoreSource",
        "new",
    ),
    (
        "crates/coven-storage/src/cloud/factory.rs",
        "CloudHomeFactory",
        "new",
    ),
    (
        "crates/coven-storage/src/cloud/factory.rs",
        "CloudHomeFactory",
        "open_s3",
    ),
    (
        "crates/coven-database/src/database_connection.rs",
        "DatabaseCore",
        "new",
    ),
    (
        "crates/coven-database/src/database_connection.rs",
        "DatabaseConnection",
        "start",
    ),
    (
        "crates/coven-database/src/database_open.rs",
        "DatabaseCore",
        "open",
    ),
    (
        "crates/coven-database/src/database_runtime.rs",
        "Database",
        "from_core",
    ),
    (
        "crates/coven-database/src/database_runtime.rs",
        "Database",
        "open",
    ),
    (
        "crates/coven-database/src/database_runtime.rs",
        "Database",
        "open_initialized_store",
    ),
    (
        "crates/coven-database/src/database_runtime.rs",
        "Database",
        "open_with_hlc_and_coven_metadata",
    ),
    (
        "crates/coven-database/src/database_runtime.rs",
        "Database",
        "open_with_hlc_and_coven_metadata_in_store_dir",
    ),
    (
        "crates/coven-database/src/database_runtime.rs",
        "Database",
        "open_in_store_dir_for_test",
    ),
    (
        "crates/coven-database/src/database_runtime.rs",
        "Database",
        "open_read_only",
    ),
    (
        "crates/coven-replication/src/sync/store/authorization/history/construction.rs",
        "AuthorizedStoreHistory",
        "authorize_writer",
    ),
    (
        "crates/coven-replication/src/sync/sync_loop.rs",
        "SyncLoopHandle",
        "new",
    ),
    ("crates/coven-replication/src/sync/store/authorization.rs", "Store", "new"),
    ("crates/coven/src/handle.rs", "CovenHandle", "new"),
    (
        "crates/coven/src/handle.rs",
        "CovenHandle",
        "create_test_store",
    ),
    ("crates/coven/src/read_handle.rs", "CovenReadHandle", "new"),
    ("crates/coven/src/coven.rs", "CovenBuilder", "open"),
    (
        "crates/coven/src/store_security.rs",
        "StoreSecurity",
        "prepare_sync_components",
    ),
    (
        "crates/coven/src/store_security.rs",
        "StoreSecurity",
        "load_store",
    ),
    (
        "crates/coven-replication/src/sync/store/device_join/joiner.rs",
        "PendingDeviceJoinObservation",
        "into_joining_store",
    ),
    (
        "crates/coven-replication/src/sync/store/device_join/joiner.rs",
        "PendingDeviceJoinAuthority",
        "prepare_same_principal_completion",
    ),
    ("crates/coven-replication/src/sync/store/authorization.rs", "Store", "create"),
    ("crates/coven-replication/src/sync/store/authorization.rs", "Store", "open"),
    ("crates/coven-replication/src/sync/store/authorization.rs", "Store", "load"),
    (
        "crates/coven-replication/src/sync/store/authorization/history/construction.rs",
        "AuthorizedStoreHistory",
        "finish_initialization",
    ),
    (
        "crates/coven-replication/src/sync/store/snapshots/image.rs",
        "PreparedSnapshotBootstrap",
        "install",
    ),
    (
        "crates/coven-replication/src/sync/cycle.rs",
        "PreparedSyncComponents",
        "prepare",
    ),
    (
        "crates/coven-replication/src/sync/cycle.rs",
        "PreparedSyncComponents",
        "initialize",
    ),
    (
        "crates/coven-replication/src/sync/cycle.rs",
        "SyncComponents",
        "from_retained_test_device",
    ),
    (
        "crates/coven-replication/src/sync/test_owner_graph.rs",
        "TestOwnerGraph",
        "new",
    ),
    (
        "crates/coven-database/src/test_support/synthetic_store.rs",
        "Database",
        "open_synthetic_for_test",
    ),
    (
        "crates/coven-database/src/test_support/synthetic_store.rs",
        "Database",
        "open_synthetic_with_hlc_for_test",
    ),
    (
        "crates/coven-domain/src/joining/transport_tests.rs",
        "TransportFixture",
        "build_with_members",
    ),
    (
        "crates/coven/src/handle_tests/join_through_the_facade.rs",
        "FacadeFixture",
        "build_with_eager_images",
    ),
    (
        "crates/coven-replication/src/sync/store/reclaim/tests.rs",
        "ReclaimJourneyFixture",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/reclaim/baseline_tests.rs",
        "StandingAcknowledgementFixture",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/reclaim/audience_blob_order_tests.rs",
        "AudienceBlobPackageFixture",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/commit_publication/operation/commit_plan/tests/merge_fixture.rs",
        "PreparedWriteFixture",
        "prepare",
    ),
    (
        "crates/coven-replication/src/sync/cycle_tests.rs",
        "SamePrincipalApprovalFixture",
        "prepare",
    ),
    (
        "crates/coven-replication/src/sync/store/membership/tests.rs",
        "MergeFixture",
        "new",
    ),
    (
        "crates/coven-replication/src/sync/store_history_checkpoint_tests.rs",
        "PublishedHistory",
        "publish",
    ),
    (
        "crates/coven-replication/src/sync/store/snapshots/circle_tests.rs",
        "CircleSnapshotFixture",
        "initialize",
    ),
    (
        "crates/coven-replication/src/blob/delete_tests.rs",
        "TombstoneCollector",
        "load",
    ),
    (
        "crates/coven-replication/src/blob/upload_tests.rs",
        "UploadFixture",
        "with_home",
    ),
    (
        "crates/coven-replication/src/sync/pull_tests.rs",
        "PersistedCycleRemoval",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/pull_tests/browsable_versions.rs",
        "BrowsableFixture",
        "new",
    ),
    (
        "crates/coven-replication/src/sync/store/circles/tests/recovery.rs",
        "RevokedOperation",
        "prepare",
    ),
    (
        "crates/coven-replication/src/sync/store/circles/tests/publication.rs",
        "ClosingFounderCircle",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/circles/tests/publication.rs",
        "SilentParticipantCircle",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/circles/tests/resolution.rs",
        "ConflictFixture",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/circles/tests/rotation_required.rs",
        "RotationFixture",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/circles/tests/rotation_required/restoration.rs",
        "CircleWithOneMember",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/circles/tests/rotation_required/restoration.rs",
        "ActiveMemberCircleSnapshot",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/owner_role_promotion/tests.rs",
        "PromotionCandidate",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/store/pull/tests.rs",
        "EffectiveAccessFixture",
        "create",
    ),
    (
        "crates/coven-replication/src/sync/store/snapshots/image_tests/scoped.rs",
        "PublishedScopedSnapshot",
        "publish",
    ),
    (
        "crates/coven-replication/src/sync/snapshot_membership_history_tests.rs",
        "MemberRemovalHistory",
        "create",
    ),
    (
        "crates/coven-replication/src/sync/acknowledged_history_tests.rs",
        "AcknowledgedHistory",
        "publish",
    ),
    (
        "crates/coven/src/coven_tests.rs",
        "RemoteOnlyStoreBlob",
        "create",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestDevice",
        "create",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestDevice",
        "create_with_database",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestDevice",
        "load",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestDevice",
        "load_with_database",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestDevice",
        "open_with_database",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestDevice",
        "activate_joined_from_snapshot",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "create",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "create_encrypted",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "create_browsable",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "create_with_protection",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "create_with_protection_database",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "bind_founder_device",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "open_store_with_identity",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "open_store_with_storage",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "open_founder_store_with_storage",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "bind_device_in",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "bind_device",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "activate_joined_device",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "activate_joined_device_from_snapshot",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "bind_store_device",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "admit_and_activate_peer",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "open_into",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "open_into_store_database",
    ),
    (
        "crates/coven-database/src/database_connection/snapshot_preparation.rs",
        "DatabaseConnection",
        "prepare_snapshot_database",
    ),
    (
        "crates/coven-replication/src/sync/store/owner_role_promotion/tests.rs",
        "PromotionCandidate",
        "build_with_connection",
    ),
    (
        "crates/coven-replication/src/sync/store/pull/seeded_snapshot_adoption_tests.rs",
        "SnapshotAdoptionReceiver",
        "join",
    ),
    (
        "crates/coven-replication/src/sync/store/pull/seeded_snapshot_adoption_tests.rs",
        "SnapshotAdoptionReceiver",
        "restart",
    ),
    (
        "crates/coven-replication/src/sync/store/pull/write_rebase_tests.rs",
        "RebaseFixture",
        "with_schema",
    ),
    (
        "crates/coven-replication/src/sync/store/reclaim/offline_peer_tests.rs",
        "OfflinePeerFixture",
        "build",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestDevice",
        "activate_joined_with_clock",
    ),
    (
        "crates/coven-replication/src/sync/test_helpers.rs",
        "TestStore",
        "activate_joined_device_with_clock",
    ),
    (
        "crates/coven-replication/src/sync/store/installed_device_join_snapshot_test_support.rs",
        "InstalledDeviceJoinSnapshot",
        "complete_and_assert_circle_snapshot_clock_for_test",
    ),
];
