//! The policy file of §20.2. It names only what exists; each crate's PR adds
//! the rows for what it introduces. `owner_policy_tests.rs` holds the guard
//! tests that fail when a row names a crate, file, type or method that is not
//! in the workspace.

use crate::policy::{Capabilities, Capability, Gate, Policy};

pub(crate) const POLICY: Policy = Policy {
    // Rows are added as crates land, in §20.1's order: coven-foundation,
    // coven-crypto, coven-merge, coven-format, coven-database, coven-storage,
    // coven-sync, coven.
    crate_order: &[
        "coven-foundation",
        "coven-crypto",
        "coven-merge",
        "coven-format",
        "coven-database",
        "coven-storage",
        "coven-sync",
        "coven",
    ],
    separated_crates: &[("coven-database", "coven-storage")],
    capabilities: CAPABILITIES,
    database_schema: Some((
        "crates/coven-database/src/internal_schema.rs",
        &["coven_tables"],
    )),
    composition_roots: &[
        ("crates/coven/src/lib_tests.rs", "Network", "new"),
        ("crates/coven/src/storage_tests.rs", "Fixture", "new"),
        (
            "crates/coven-storage/src/providers/connector.rs",
            "ProviderConnector",
            "connect",
        ),
        ("crates/coven/tests/fixtures/bootstrap.rs", "Owner", "new"),
        (
            "crates/coven/src/bootstrap.rs",
            "<free>",
            "restore_from_code",
        ),
        (
            "crates/coven/src/bootstrap.rs",
            "<free>",
            "restore_from_keychain",
        ),
        (
            "crates/coven/src/bootstrap.rs",
            "<free>",
            "join_with_invite",
        ),
        (
            "crates/coven/src/bootstrap.rs",
            "<free>",
            "prepare_and_load",
        ),
        (
            "crates/coven/src/bootstrap_commit.rs",
            "<free>",
            "publish_bootstrap",
        ),
        (
            "crates/coven-foundation/src/files/bootstrap.rs",
            "<free>",
            "reserve_bootstrap_directory",
        ),
        (
            "crates/coven-foundation/src/files/recovery.rs",
            "DatabaseRecovery",
            "check",
        ),
        (
            "crates/coven-foundation/src/files/directory.rs",
            "StoreDir",
            "download",
        ),
        ("crates/coven/src/builder.rs", "OpeningStore", "open"),
        (
            "crates/coven/src/builder.rs",
            "OpeningStore",
            "open_reloading",
        ),
        ("crates/coven/src/builder.rs", "OpeningOwners", "sync"),
        ("crates/coven/src/builder.rs", "OpeningOwners", "handle"),
        (
            "crates/coven/src/builder.rs",
            "CovenBuilder",
            "open_reloading",
        ),
        (
            "crates/coven-database/src/database_builder.rs",
            "DatabaseBuilder",
            "open_reloading_locked",
        ),
        (
            "crates/coven-foundation/src/files/recovery.rs",
            "DatabaseRecovery",
            "begin",
        ),
        (
            "crates/coven-foundation/src/files/directory.rs",
            "StoreDir",
            "recover_database",
        ),
        ("crates/coven-sync/src/sync_loop.rs", "SyncLoop", "new"),
        ("crates/coven-sync/src/sync_loop.rs", "SyncRun", "connect"),
        ("crates/coven-sync/src/sync_loop.rs", "SyncRun", "setup"),
        ("crates/coven-sync/src/sync_loop.rs", "SyncLoop", "setup"),
        ("crates/coven-sync/src/sync_loop.rs", "SyncLoop", "unlock"),
        ("crates/coven-sync/src/operations.rs", "Operations", "new"),
        ("crates/coven-sync/src/files_tests.rs", "Fixture", "new"),
        ("crates/coven-sync/src/files_tests.rs", "Fixture", "reopen"),
        (
            "crates/coven-database/src/database_builder.rs",
            "DatabaseBuilder",
            "open_locked",
        ),
        (
            "crates/coven-storage/src/providers/s3.rs",
            "S3Storage",
            "new",
        ),
        (
            "crates/coven-database/src/database_builder.rs",
            "DatabaseBuilder",
            "open_graph",
        ),
        (
            "crates/coven-database/src/database_builder.rs",
            "DatabaseBuilder",
            "open_read_graph",
        ),
        ("crates/coven/src/builder.rs", "CovenBuilder", "new"),
        ("crates/coven/src/builder.rs", "CovenBuilder", "open"),
        ("crates/coven/src/builder.rs", "CovenBuilder", "open_graph"),
        ("crates/coven/src/builder.rs", "CovenBuilder", "database"),
        ("crates/coven/src/builder.rs", "CovenBuilder", "keychain"),
        ("crates/coven/src/builder.rs", "CovenBuilder", "owners"),
        (
            "crates/coven/src/bootstrap.rs",
            "<free>",
            "bootstrap_device",
        ),
        ("crates/coven/src/builder.rs", "CovenBuilder", "read_graph"),
        (
            "crates/coven/src/builder.rs",
            "CovenBuilder",
            "open_read_only",
        ),
        ("crates/coven/src/builder.rs", "CovenBuilder", "make_keys"),
        (
            "crates/coven/src/builder.rs",
            "CovenBuilder",
            "make_identity",
        ),
        ("crates/coven/src/coven.rs", "Coven", "builder"),
        ("crates/coven/src/coven.rs", "Coven", "create_store"),
        ("crates/coven/src/coven.rs", "Coven", "delete_store"),
        ("crates/coven/src/test_utils.rs", "TestCoven", "new"),
        (
            "crates/coven/src/test_utils.rs",
            "TestCoven",
            "keep_store_keys",
        ),
        ("crates/coven/src/test_utils.rs", "TestCoven", "builder"),
        (
            "crates/coven/src/test_utils.rs",
            "TestCoven",
            "create_store",
        ),
        (
            "crates/coven/src/test_utils.rs",
            "TestCoven",
            "delete_store",
        ),
    ],
    lifetime_authorities: &[
        ("SyncRun", "SyncLoop"),
        ("OperationRun", "Operations"),
        ("RunningOperations", "Operations"),
        ("ReconfigurableLiveQuery", "Database"),
        ("LiveQuery", "Database"),
    ],
    // These methods derive a scoped capability from their injected directory.
    // They do not acquire an unrelated directory or file for another owner.
    capability_factories: &[
        (
            "crates/coven-foundation/src/files/layout.rs",
            "StoreLayout",
            "begin_bootstrap",
            "BootstrapStore",
        ),
        (
            "crates/coven-foundation/src/files/bootstrap.rs",
            "BootstrapStore",
            "directory",
            "StoreDir",
        ),
        (
            "crates/coven-foundation/src/files/directory.rs",
            "StoreDir",
            "recover_database",
            "DatabaseRecovery",
        ),
        (
            "crates/coven-foundation/src/files/directory.rs",
            "StoreDir",
            "download",
            "DownloadFile",
        ),
        (
            "crates/coven-foundation/src/files/download.rs",
            "DownloadFile",
            "create_writer",
            "FileWriter",
        ),
        (
            "crates/coven-foundation/src/files/directory.rs",
            "StoreDir",
            "lock_for_deletion",
            "StoreDeletionLock",
        ),
        (
            "crates/coven-foundation/src/files/directory.rs",
            "StoreDir",
            "lock_read_only",
            "StoreReadLock",
        ),
        (
            "crates/coven-foundation/src/files/layout.rs",
            "StoreLayout",
            "create_store_dir_with",
            "StoreDir",
        ),
        (
            "crates/coven-foundation/src/files/atomic_file.rs",
            "AtomicFile",
            "create_writer",
            "FileWriter",
        ),
        (
            "crates/coven-foundation/src/files/directory.rs",
            "StoreDir",
            "lock_exclusive",
            "StoreLock",
        ),
        (
            "crates/coven-foundation/src/files/layout.rs",
            "StoreLayout",
            "store_dir",
            "StoreDir",
        ),
        (
            "crates/coven-foundation/src/files/layout.rs",
            "StoreLayout",
            "create_store_dir",
            "StoreDir",
        ),
        (
            "crates/coven-foundation/src/files/directory.rs",
            "StoreDir",
            "owned_file",
            "AtomicFile",
        ),
        (
            "crates/coven-foundation/src/files/directory.rs",
            "StoreDir",
            "file",
            "AtomicFile",
        ),
    ],
    // These are the leaf capabilities. Owners retaining them receive them
    // through constructors; their implementations keep raw OS handles private.
    capability_types: &[
        "Clock",
        "ClockRef",
        "SystemClock",
        "IdSource",
        "IdSourceRef",
        "UuidIds",
        "StoreLayout",
        "BootstrapStore",
        "StoreDir",
        "AtomicFile",
        "DownloadFile",
        "FileWriter",
        "FileReader",
        "StoreLock",
        "StoreReadLock",
        "StoreDeletionLock",
        "DatabaseRecovery",
        "Keychain",
        "StoreKeychain",
        "KeyringCustody",
        "StoreKeyCustody",
        "MemberKeyCustody",
        "StorageConnector",
        "Storage",
        "CloudKitOps",
        "OAuthClients",
        "OAuthSession",
        "DatabaseConnection",
    ],
    capability_traits: &[
        "Clock",
        "IdSource",
        "StoreKeyCustody",
        "MemberKeyCustody",
        "StorageConnector",
        "Storage",
        "CloudKitOps",
    ],
    construction_only_capability_types: &[
        "BootstrapStore",
        "StoreDir",
        "StoreLock",
        "StoreReadLock",
        "StoreDeletionLock",
        "DatabaseRecovery",
        "AtomicFile",
        "DownloadFile",
        "FileWriter",
        "ClockRef",
        "IdSourceRef",
        "Keychain",
        "StoreKeychain",
        "OAuthClients",
        "OAuthSession",
        "DatabaseConnection",
    ],
    non_owner_types: &[
        "KeyCustody",
        "IdentityCustody",
        "Command",
        "SyncCommand",
        "Request",
    ],
    // Writes and pending deletions borrow the database's retained connection,
    // StoreDir and id source; app SQL receives none of those dependencies.
    borrowed_facade_types: &[
        "Circles",
        "FileWrite",
        "FileRemovals",
        "SqlReadContext",
        "Read",
        "ReadOwner",
        "ChangeCapture",
        "StreamCapture",
        "MigrationContext",
        "SqlContext",
        "SqlTransaction",
        "ReaderLease",
        "AppView",
        "MergeStore",
        "WriteMetadata",
        "DatabaseRemovalView",
        "WriteApply",
    ],
    root_owner_types: &[
        "StorageConnections",
        "SyncLoop",
        "Operations",
        "Database",
        "DatabaseReadHandle",
        "StoreLogSync",
        "DeviceLogSync",
        "RestoreCodes",
        "CovenHandle",
        "CovenReadHandle",
        "Files",
        "FileDatabase",
    ],
    task_types: &[
        "UploadActivity",
        "SyncRun",
        "OperationRun",
        "RunningOperations",
        "Circles",
        "CacheReservation",
        "UploadedFile",
        "SnapshotInput",
        "SnapshotWriteParts",
        "SnapshotTransfer",
        "FileTransfer",
        "FileRangeStream",
        "UploadsLiveQuery",
        "RowsPinnedLiveQuery",
        "FileWorker",
        "LocalFileStream",
        "FileStream",
        "FileStaging",
        "FileWrite",
        "FileRemovals",
        "SqlReadContext",
        "Read",
        "ReadOwner",
        "ChangeCapture",
        "StreamCapture",
        "LiveQuery",
        "ReconfigurableLiveQuery",
        "SqlTransaction",
        "ReaderLease",
        "AppView",
        "MergeStore",
        "WriteMetadata",
        "DatabaseRemovalView",
        "WriteApply",
    ],
    internal_dependency_types: &["DatabaseConnection"],
    always_forbidden_returns: &[],
    closed_session_types: &[
        "FileWrite",
        "FileRemovals",
        "SqlReadContext",
        "MigrationContext",
        "SqlContext",
        "AppView",
        "MergeStore",
        "WriteMetadata",
        "DatabaseRemovalView",
        "WriteApply",
    ],
    field_capability_types: &[],
    raw_provider_operations: &[],
    derived_services: &[],
    unexported_capability_types: &[],
    exportable_capability_outputs: &[],
};

/// §20.2's table. Each capability's homes are the paths the spec assigns it;
/// a home inside a crate that has not landed yet covers nothing until it does.
const CAPABILITIES: Capabilities = Capabilities {
    network: Capability {
        name: "network",
        homes: &["crates/coven-storage/src/providers/"],
        gates: &[
            Gate {
                kind: "HTTP client (reqwest)",
                crates: &["reqwest"],
                path_patterns: &[],
                method_patterns: &[],
            },
            Gate {
                kind: "HTTP server (axum)",
                crates: &["axum"],
                path_patterns: &[],
                method_patterns: &[],
            },
            Gate {
                kind: "AWS SDK",
                crates: &[
                    "aws_config",
                    "aws_sdk_s3",
                    "aws_sdk_sts",
                    "aws_credential_types",
                    "aws_smithy_http_client",
                    "aws_smithy_runtime_api",
                    "aws_smithy_types",
                    "smithy_transport_reqwest",
                ],
                path_patterns: &[],
                method_patterns: &[],
            },
            Gate {
                kind: "browser opener (open)",
                crates: &["open"],
                path_patterns: &[],
                method_patterns: &[],
            },
            Gate {
                kind: "sockets",
                crates: &[],
                path_patterns: &[&["std", "net"], &["tokio", "net"]],
                method_patterns: &[],
            },
        ],
    },
    cryptography: Capability {
        name: "cryptography",
        homes: &["crates/coven-crypto/src/"],
        gates: &[
            Gate {
                kind: "signing keys (ed25519-dalek)",
                crates: &["ed25519_dalek"],
                path_patterns: &[],
                method_patterns: &[],
            },
            Gate {
                kind: "sealed-box keys (crypto_box / x25519-dalek)",
                crates: &["crypto_box", "x25519_dalek"],
                path_patterns: &[],
                method_patterns: &[],
            },
            Gate {
                kind: "AEAD cipher (chacha20poly1305)",
                crates: &["chacha20poly1305"],
                path_patterns: &[],
                method_patterns: &[],
            },
            Gate {
                kind: "key derivation (hkdf / argon2)",
                crates: &["hkdf", "argon2"],
                path_patterns: &[],
                method_patterns: &[],
            },
            Gate {
                kind: "keyed hashes (hmac / sha2)",
                crates: &["hmac", "sha2"],
                path_patterns: &[],
                method_patterns: &[],
            },
            Gate {
                kind: "randomness",
                crates: &["rand", "rand_core", "getrandom"],
                path_patterns: &[&["OsRng"], &["thread_rng"], &["ThreadRng"]],
                method_patterns: &[],
            },
        ],
    },
    // The raw handles and coven's own SQL are the database boundary's subject
    // (`database_boundary.rs`); this row names the database's home and the
    // SQLite library beneath rusqlite.
    sqlite: Capability {
        name: "SQLite",
        homes: &["crates/coven-database/src/"],
        gates: &[Gate {
            kind: "SQLite library (rusqlite / libsqlite3-sys)",
            crates: &["rusqlite", "libsqlite3_sys"],
            path_patterns: &[],
            method_patterns: &[],
        }],
    },
    keychain: Capability {
        name: "OS keychain",
        homes: &["crates/coven-crypto/src/custody/"],
        gates: &[Gate {
            kind: "platform keychain",
            crates: &[
                "keyring",
                "keyring_core",
                "apple_native_keyring_store",
                "android_native_keyring_store",
                "windows_native_keyring_store",
                "zbus_secret_service_keyring_store",
                "security_framework",
            ],
            path_patterns: &[],
            method_patterns: &[],
        }],
    },
    time: Capability {
        name: "current time",
        homes: &["crates/coven-foundation/src/clock.rs"],
        gates: &[Gate {
            kind: "system clock",
            crates: &[],
            path_patterns: &[
                &["SystemTime", "now"],
                &["Instant", "now"],
                &["Utc", "now"],
                &["Local", "now"],
                &["OffsetDateTime", "now_utc"],
                &["OffsetDateTime", "now_local"],
            ],
            method_patterns: &[],
        }],
    },
    // Only generation is gated: parsing and validating an id is a
    // deterministic transformation any module may perform.
    ids: Capability {
        name: "new ids",
        homes: &["crates/coven-foundation/src/id_source.rs"],
        gates: &[Gate {
            kind: "id generation (uuid)",
            crates: &[],
            path_patterns: &[
                &["Uuid", "new_v4"],
                &["Uuid", "new_v7"],
                &["Uuid", "now_v7"],
            ],
            method_patterns: &[],
        }],
    },
    files: Capability {
        name: "files on disk",
        homes: &["crates/coven-foundation/src/files/"],
        gates: &[Gate {
            kind: "filesystem",
            crates: &["tempfile"],
            path_patterns: &[
                &["std", "fs"],
                &["tokio", "fs"],
                &["unix", "fs"],
                &["windows", "fs"],
                &["rustix", "fs"],
                &["windows_sys", "Win32", "Storage", "FileSystem"],
            ],
            method_patterns: &[],
        }],
    },
    // Database calls await blocking work while retaining the database owner.
    // The operation owner also retains and stops its journal worker.
    // File work is owned by Files and advances on commits or explicit requests.
    runtimes: Capability {
        name: "runtimes and spawned work",
        homes: &[
            "crates/coven-database/src/database.rs",
            "crates/coven-database/src/database_operations.rs",
            "crates/coven-database/src/database_snapshots.rs",
            "crates/coven-database/src/database_file_retention.rs",
            "crates/coven-sync/src/sync_loop.rs",
            "crates/coven-sync/src/operations.rs",
            "crates/coven-sync/src/restore_codes.rs",
            "crates/coven-database/src/database_sync.rs",
            "crates/coven-database/src/file_staging.rs",
            "crates/coven-database/src/file_database.rs",
            "crates/coven-database/src/file_keep.rs",
            "crates/coven-sync/src/file_keep.rs",
            "crates/coven-sync/src/files.rs",
            "crates/coven-sync/src/file_read.rs",
            "crates/coven-database/src/database_builder.rs",
            "crates/coven-database/src/local_file.rs",
            "crates/coven-foundation/src/files/layout.rs",
            "crates/coven-foundation/src/files/atomic_file.rs",
            "crates/coven/src/storage.rs",
            "crates/coven/src/coven.rs",
            "crates/coven/src/handle.rs",
            "crates/coven/src/read_handle.rs",
        ],
        gates: &[
            Gate {
                kind: "runtime construction",
                crates: &[],
                path_patterns: &[
                    &["Runtime", "new"],
                    &["Builder", "new_current_thread"],
                    &["Builder", "new_multi_thread"],
                ],
                method_patterns: &[],
            },
            Gate {
                kind: "ambient runtime acquisition",
                crates: &[],
                path_patterns: &[&["Handle", "current"], &["Handle", "try_current"]],
                method_patterns: &[],
            },
            Gate {
                kind: "thread or task spawn",
                crates: &[],
                path_patterns: &[
                    &["tokio", "spawn"],
                    &["task", "spawn"],
                    &["task", "spawn_blocking"],
                    &["task", "spawn_local"],
                    &["thread", "spawn"],
                ],
                method_patterns: &["spawn", "spawn_blocking", "spawn_local"],
            },
        ],
    },
};

#[cfg(test)]
#[path = "owner_policy_tests.rs"]
mod tests;
