import CovenIO

#print axioms CovenIO.scan_terminal
#print axioms CovenIO.scan_received
#print axioms CovenIO.scan_event_bounds
#print axioms CovenIO.discovery_complete
#print axioms CovenIO.delivery_from_pass
#print axioms CovenIO.permanent_prefix_available
#print axioms CovenIO.provider_prefix_available
#print axioms CovenIO.permanent_receipt_exact
#print axioms CovenIO.recent_prefix_available
#print axioms CovenIO.recent_return_complete
#print axioms CovenIO.writer_discovered
#print axioms CovenIO.through_time
#print axioms CovenIO.Downloads.first_unmet
#print axioms CovenIO.Downloads.one_pending
#print axioms CovenIO.Downloads.pending_replaced
#print axioms CovenIO.Downloads.failure_atomic
#print axioms CovenIO.Downloads.progress_never_decreases
#print axioms CovenIO.Downloads.committed_ranges_unique
#print axioms CovenIO.Downloads.completion_has_all_ranges
#print axioms CovenIO.Downloads.committed_range_checked
#print axioms CovenIO.Downloads.permanent_never_retries
#print axioms CovenIO.Downloads.temporary_uses_shared_delay
#print axioms CovenIO.Downloads.removed_not_waiting
#print axioms CovenIO.Downloads.replaced_not_waiting
#print axioms CovenIO.Downloads.active_absence_retries
#print axioms CovenIO.Downloads.eviction_preserves_refusal
#print axioms CovenIO.Downloads.completed_eviction_does_not_refill
#print axioms CovenIO.Downloads.key_wait_names_parent
#print axioms CovenIO.Examples.incomparable_latest
#print axioms CovenIO.Examples.latest_selected_incomparable
#print axioms CovenIO.Examples.incomparable_deletion_impossible
#print axioms CovenIO.Examples.newest_snapshot_misses_deleted_write
#print axioms CovenIO.Examples.delete_two_after_three
#print axioms CovenIO.Examples.snapshot_next_number_wrong
#print axioms CovenIO.Examples.loaded_snapshot_can_become_stale
#print axioms CovenIO.Examples.away_write_miss
#print axioms CovenIO.Examples.pass_crosses_deadline
#print axioms CovenIO.Examples.clock_jump_defeats_recent_miss
#print axioms CovenIO.Examples.positions_not_index
#print axioms CovenIO.Examples.timestamp_not_frontier
#print axioms CovenIO.Examples.no_request_error_insufficient
#print axioms CovenIO.Examples.refused_scan_incomplete
#print axioms CovenIO.Examples.successful_execution
#print axioms CovenIO.Examples.idle_three_devices
#print axioms CovenIO.Examples.disk_failure_keeps_progress
#print axioms CovenIO.Examples.replacement_needs_landing_frontier
#print axioms CovenIO.Examples.retired_write_boundary_and_restore
#print axioms CovenIO.Examples.fresh_gate_boundaries
#print axioms CovenIO.Examples.last_send_settles
#print axioms CovenIO.Examples.pass_can_download_file
#print axioms CovenIO.Examples.upload_parts_use_gate
#print axioms CovenIO.Examples.upload_uses_last_completed_catchup
#print axioms CovenIO.failed_request_counted
#print axioms CovenIO.executed_scan
#print axioms CovenIO.accepted_miss_is_recent
#print axioms CovenIO.complete_pass
#print axioms CovenIO.Publication.step_valid
#print axioms CovenIO.Publication.reachable_valid
#print axioms CovenIO.Publication.gap_free
#print axioms CovenIO.Publication.reservations_irrevocable
#print axioms CovenIO.Publication.publication_fixed
#print axioms CovenIO.Publication.exact_path_prefix
#print axioms CovenIO.Publication.interleaved_valid
#print axioms CovenIO.Refinement.retained_hit
#print axioms CovenIO.Refinement.pass_supplies_input
#print axioms CovenIO.Refinement.merge_step_realized
#print axioms CovenIO.Refinement.storelog_step_realized
#print axioms CovenIO.Refinement.coupled_write_consumed
#print axioms CovenIO.Refinement.finality_precondition
#print axioms CovenIO.recent_write_protected
#print axioms CovenIO.unresolved_preserves_checkpoint
#print axioms CovenIO.exact_boundary_discovers
#print axioms CovenIO.miss_before_retention
#print axioms CovenIO.Retired.drained_not_polled
#print axioms CovenIO.Retired.drained_not_named
#print axioms CovenIO.Retired.write_verdict_agrees
#print axioms CovenIO.Retired.dropped_retirement_restores
#print axioms CovenIO.Retired.kept_retirement_rejects
#print axioms CovenIO.Retired.final_retirement_seen
#print axioms CovenIO.Retired.publication_before_deadline
#print axioms CovenIO.Retired.retirement_closed
#print axioms CovenIO.Retired.drain_complete
#print axioms CovenIO.Retired.failed_scan_not_complete
#print axioms CovenIO.Retired.completed_scan_retained
#print axioms CovenIO.create_once
#print axioms CovenIO.create_visible
#print axioms CovenIO.replacement_revision
#print axioms CovenIO.scoped_listing
#print axioms CovenIO.status_is_exact
#print axioms CovenIO.serve_get
#print axioms CovenIO.serve_occupied
#print axioms CovenIO.served_transition
#print axioms CovenIO.permanent_step
#print axioms CovenIO.storage_time_monotone
#print axioms CovenIO.permanent_retained
#print axioms CovenIO.old_immutable_step
#print axioms CovenIO.provider_time_grows
#print axioms CovenIO.old_immutable_present
#print axioms CovenIO.exposure_survives
#print axioms CovenIO.idle_requests
#print axioms CovenIO.idle_two_listings
#print axioms CovenIO.idle_gets
#print axioms CovenIO.scan_cost
#print axioms CovenIO.fetch_ahead_cost
#print axioms CovenIO.retained_never_fetched
#print axioms CovenIO.shared_in_flight
#print axioms CovenIO.reopen_retains_bytes
#print axioms CovenIO.cache_keeps_unless_evicted
#print axioms CovenIO.no_duplicate_download
#print axioms CovenIO.send_requires_check
#print axioms CovenIO.check_precedes_send
#print axioms CovenIO.pass_no_file_uploads
#print axioms CovenIO.upload_worker_gated
#print axioms CovenIO.expired_sends_nothing
#print axioms CovenIO.invalidation_clears
#print axioms CovenIO.Waiting.delay_cap
#print axioms CovenIO.Waiting.delay_positive
#print axioms CovenIO.Waiting.delay_at_cap
#print axioms CovenIO.Waiting.restart_bounded
#print axioms CovenIO.Waiting.app_retry_keeps_cooldown
#print axioms CovenIO.Waiting.span
#print axioms CovenIO.Waiting.rate
#print axioms CovenIO.Waiting.waits_rate
#print axioms CovenIO.Waiting.one_second_bound
#print axioms CovenIO.Waiting.capped_bound
#print axioms CovenIO.late_snapshot_ignored
#print axioms CovenIO.old_upload_before_deletion
#print axioms CovenIO.symmetric_in_flight_impossible
#print axioms CovenIO.maturity_survives_new_snapshots
#print axioms CovenIO.eligible_after_day
#print axioms CovenIO.SnapshotPublication.run_append
#print axioms CovenIO.SnapshotPublication.tick_preserves_deleted
#print axioms CovenIO.loaded_snapshot_complete
#print axioms CovenIO.catchup_miss_after_sample
#print axioms CovenIO.Examples.incomparable_history
#print axioms CovenIO.Examples.in_flight_race_excluded
#print axioms CovenIO.Examples.late_upload_lands_but_does_not_count
#print axioms CovenIO.Examples.fresh_selection_race
#print axioms CovenIO.Examples.fresh_selection_reader_misses
#print axioms CovenIO.Examples.symmetric_deletions_excluded
#print axioms CovenIO.Examples.cleanup_ready_reachable
#print axioms CovenIO.Examples.no_cleanup_deadline
#print axioms CovenIO.Examples.busy_catalog
#print axioms CovenIO.Examples.busy_write_facts
#print axioms CovenIO.Examples.busy_unused_path
#print axioms CovenIO.Examples.busy_step
#print axioms CovenIO.Examples.busy_run
#print axioms CovenIO.Examples.busy_never_deletes
#print axioms CovenIO.Examples.busy_retains_first
#print axioms CovenIO.Examples.busy_eligible
#print axioms CovenIO.Examples.busy_cleanup_unbounded
#print axioms CovenIO.Examples.reader_race_despite_dominance
#print axioms CovenIO.Examples.snapshot_age_boundaries
#print axioms CovenIO.Examples.loaded_snapshot_advances
