import CovenStorage

#print axioms CovenStorage.Clocks.stamp_after_latest
#print axioms CovenStorage.Clocks.stamp_value
#print axioms CovenStorage.Clocks.representable_stamp_exists
#print axioms CovenStorage.Clocks.wall_ahead_uses_zero_counter
#print axioms CovenStorage.Clocks.wall_behind_increments
#print axioms CovenStorage.Clocks.stamp_after_every_read
#print axioms CovenStorage.Clocks.different_devices_distinct
#print axioms CovenStorage.Clocks.observe_upper
#print axioms CovenStorage.Clocks.snapshot_upper
#print axioms CovenStorage.Clocks.stamp_after_snapshot
#print axioms CovenStorage.Clocks.no_clock_hold
#print axioms CovenStorage.Clocks.waiting_is_not_seen
#print axioms CovenStorage.Clocks.age_never_early
#print axioms CovenStorage.Clocks.finality_age_never_early
#print axioms CovenStorage.Clocks.finality_window_partition
#print axioms CovenStorage.Clocks.wall_jump_changes_no_age_or_retry
#print axioms CovenStorage.Clocks.retry_delay_bounded

#print axioms CovenStorage.Examples.unsent_restore_loss
#print axioms CovenStorage.Examples.restore_from_deleted_log_detected
#print axioms CovenStorage.Examples.outstanding_reservation_is_not_stale
#print axioms CovenStorage.Examples.single_live_restore_nonce_separation
#print axioms CovenStorage.Examples.rollback_conversion_changes_plaintext
#print axioms CovenStorage.Examples.fewer_than_two_attempts_no_reuse
#print axioms CovenStorage.Examples.two_live_copies_race
#print axioms CovenStorage.Examples.concurrent_replacements
#print axioms CovenStorage.Examples.duplicate_delivery_after_reset
#print axioms CovenStorage.Examples.status_cases
#print axioms CovenStorage.Examples.older_upload_cannot_restore_photo
#print axioms CovenStorage.Examples.changed_source_not_encrypted
#print axioms CovenStorage.Examples.clock_boundaries
#print axioms CovenStorage.Examples.storage_age_boundaries

#print axioms CovenStorage.Files.status_agreement
#print axioms CovenStorage.Files.presence_wins
#print axioms CovenStorage.Files.read_error_not_missing
#print axioms CovenStorage.Files.absent_active_uploading
#print axioms CovenStorage.Files.attachment_atomic
#print axioms CovenStorage.Files.finish_reports_result
#print axioms CovenStorage.Files.completion_changes_no_row
#print axioms CovenStorage.Files.completion_retires_both
#print axioms CovenStorage.Files.completion_idempotent
#print axioms CovenStorage.Files.unequal_bytes_keep_queue
#print axioms CovenStorage.Files.encrypted_chunk_is_captured
#print axioms CovenStorage.Files.file_retries_fixed

#print axioms CovenStorage.ends_comm
#print axioms CovenStorage.ends_assoc
#print axioms CovenStorage.ends_idempotent
#print axioms CovenStorage.ends_keep_both
#print axioms CovenStorage.sends_require_check
#print axioms CovenStorage.failed_scan_sends_nothing
#print axioms CovenStorage.send_has_custody
#print axioms CovenStorage.send_not_ahead
#print axioms CovenStorage.send_covers_all_evidence
#print axioms CovenStorage.replacement_has_owner
#print axioms CovenStorage.applyOnce_nodup
#print axioms CovenStorage.applyOnce_members
#print axioms CovenStorage.applyOnce_idempotent
#print axioms CovenStorage.receipt_no_duplicates
#print axioms CovenStorage.receipt_members
#print axioms CovenStorage.reset_unavailable
#print axioms CovenStorage.registration_retry_number
#print axioms CovenStorage.reset_discards_queue
#print axioms CovenStorage.reset_uses_fresh_id
#print axioms CovenStorage.reset_loads_once
#print axioms CovenStorage.commit_reserves_next
#print axioms CovenStorage.reset_first_write_new_path
#print axioms CovenStorage.non_sending_gate_emits_nothing
#print axioms CovenStorage.combined_end_keeps_completed
#print axioms CovenStorage.beyond_end_waits

#print axioms CovenStorage.create_preserves
#print axioms CovenStorage.create_publishes
#print axioms CovenStorage.retry_preserves_time
#print axioms CovenStorage.stored_history_preserved
#print axioms CovenStorage.settled_iff_equal
#print axioms CovenStorage.retry_fixed
#print axioms CovenStorage.fresh_path_separates_nonces
#print axioms CovenStorage.nonce_exclusivity
#print axioms CovenStorage.different_plaintext_separates_nonces
#print axioms CovenStorage.attempts_nonce_exclusive
#print axioms CovenStorage.retries_identical
#print axioms CovenStorage.Examples.content_free_rollback_nonce_reuse
#print axioms CovenStorage.Examples.entry_chunks_and_prefixes_separated

#print axioms CovenStorage.ReplacementRead.registration_authority
#print axioms CovenStorage.ReplacementRead.accepts_iff
#print axioms CovenStorage.ReplacementRead.before_read_counts
#print axioms CovenStorage.ReplacementRead.after_read_rejected
#print axioms CovenStorage.ReplacementRead.replacement_order_irrelevant
#print axioms CovenStorage.ReplacementRead.loaded_iff
#print axioms CovenStorage.ReplacementRead.no_duplicate_application
#print axioms CovenStorage.ReplacementRead.no_stored_write_lost
#print axioms CovenStorage.ReplacementRead.stored_object_survives
#print axioms CovenStorage.ReplacementRead.devices_converge
#print axioms CovenStorage.ReplacementRead.receipt_after_restore
#print axioms CovenStorage.ReplacementRead.old_copy_stops
#print axioms CovenStorage.ReplacementRead.observed_replacement_blocks_send
#print axioms CovenStorage.ReplacementRead.missing_custody_blocks_restore
#print axioms CovenStorage.ReplacementRead.reset_uses_new_path

#print axioms CovenStorage.ReplacementRead.Examples.racing_upload_kept
#print axioms CovenStorage.ReplacementRead.Examples.restored_and_live_copies_stop
#print axioms CovenStorage.ReplacementRead.Examples.post_read_objects_rejected
#print axioms CovenStorage.ReplacementRead.Examples.restored_copy_can_send
#print axioms CovenStorage.ReplacementRead.Examples.unsent_loss
#print axioms CovenStorage.ReplacementRead.Examples.colliding_copies_lose_one_value
