[package]
name = "coven-database"
version.workspace = true
edition.workspace = true

[features]
test-utils = []

[dependencies]
coven-crypto.workspace = true
coven-foundation.workspace = true
coven-merge.workspace = true
coven-format.workspace = true
rusqlite = { workspace = true, features = ["bundled", "session", "hooks", "preupdate_hook", "functions", "limits", "blob"] }
sqlite3-parser.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "macros", "io-util"] }
uuid.workspace = true

[dev-dependencies]
coven-format = { workspace = true, features = ["test-utils"] }
rusqlite = { workspace = true, features = ["trace"] }
coven-foundation = { workspace = true, features = ["test-utils"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "net", "fs"] }

[lints]
workspace = true
